# Generated by Django 3.2.5 on 2022-01-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admission_category',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='batch',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cgpa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seat_no',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
