# Generated by Django 3.2.5 on 2022-01-31 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20220131_1926'),
        ('users', '0003_auto_20220131_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.department'),
        ),
    ]
