# Generated by Django 3.2.5 on 2022-01-31 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
                ('credit_hours', models.IntegerField()),
                ('theory_hours', models.IntegerField()),
                ('practical_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=30)),
                ('open_seats', models.IntegerField()),
                ('total_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CODStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_dept_std', to='courses.department')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_dept_std', to='courses.department')),
            ],
        ),
        migrations.CreateModel(
            name='CODCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course1', to='courses.course')),
                ('course10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course10', to='courses.course')),
                ('course11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course11', to='courses.course')),
                ('course12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course12', to='courses.course')),
                ('course2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course2', to='courses.course')),
                ('course3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course3', to='courses.course')),
                ('course4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course4', to='courses.course')),
                ('course5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course5', to='courses.course')),
                ('course6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course6', to='courses.course')),
                ('course7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course7', to='courses.course')),
                ('course8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course8', to='courses.course')),
                ('course9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course9', to='courses.course')),
                ('from_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_dept', to='courses.department')),
                ('to_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_dept', to='courses.department')),
            ],
        ),
    ]
