# Generated by Django 3.2.5 on 2022-01-31 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_department_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codcourses',
            name='course1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='codcourses',
            name='course10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='codcourses',
            name='course11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='codcourses',
            name='course12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='codcourses',
            name='course2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='codcourses',
            name='course3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='codcourses',
            name='course4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='codcourses',
            name='course5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='codcourses',
            name='course6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='codcourses',
            name='course7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='codcourses',
            name='course8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='codcourses',
            name='course9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='codcourses',
            name='from_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.department'),
        ),
        migrations.AlterField(
            model_name='codcourses',
            name='to_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.department'),
        ),
        migrations.AlterField(
            model_name='codstudents',
            name='from_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.department'),
        ),
        migrations.AlterField(
            model_name='codstudents',
            name='to_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.department'),
        ),
        migrations.AlterField(
            model_name='department_courses',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.department'),
        ),
    ]
