# Generated by Django 3.2.5 on 2022-01-31 14:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_auto_20220131_1926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CODCourses',
            new_name='BacklogCourse',
        ),
        migrations.RenameModel(
            old_name='CODStudents',
            new_name='CODStudent',
        ),
        migrations.RenameModel(
            old_name='Department_Courses',
            new_name='DeptCourseImage',
        ),
    ]
