# Generated by Django 3.2.5 on 2022-01-31 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20220131_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogcourse',
            name='course1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='backlogcourse',
            name='course10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='backlogcourse',
            name='course11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='backlogcourse',
            name='course12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='backlogcourse',
            name='course2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='backlogcourse',
            name='course3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='backlogcourse',
            name='course4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='backlogcourse',
            name='course5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='backlogcourse',
            name='course6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='backlogcourse',
            name='course7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='backlogcourse',
            name='course8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='backlogcourse',
            name='course9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course'),
        ),
    ]
