# Generated by Django 3.2.5 on 2022-01-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('S', 'Spring'), ('F', 'Fall')], default='F', max_length=10),
        ),
    ]
